## 벡터화 연산의 장점

In [2]:
import numpy as np

In [3]:
x = np.arange(1,10001)
y = np.arange(10001,20001)

## 배열을 이용하지 않고 계산 (두 벡터의 합)

In [8]:
%%time
z = np.zeros(10000)
for i in range(10000):
    z[i]=x[i]+y[i]
z

CPU times: user 12 ms, sys: 0 ns, total: 12 ms
Wall time: 11.5 ms


array([10002., 10004., 10006., ..., 29996., 29998., 30000.])

## 벡터화 연산

In [7]:
%%time
z = x+y
z

CPU times: user 271 µs, sys: 288 µs, total: 559 µs
Wall time: 359 µs


array([10002, 10004, 10006, ..., 29996, 29998, 30000])

## 벡터화 연산 예시

In [9]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

In [10]:
a == b

array([False,  True, False,  True])

In [11]:
a >= b

array([False,  True,  True,  True])

In [12]:
np.all(a==b)

False

In [13]:
c = np.array([1,2,3,4])
np.all(a==c)

True

In [14]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [15]:
np.log(a+1)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791])

## 스칼라와 벡터연산

In [16]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [18]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

## 브로드캐스팅

In [20]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [21]:
x+1

array([1, 2, 3, 4, 5])

In [22]:
x=np.arange(15).reshape(5,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [23]:
y = np.arange(3)
y

array([0, 1, 2])

In [24]:
x+y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13],
       [12, 14, 16]])

In [25]:
y = np.arange(5).reshape(-1,1)
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [26]:
x+y

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

## 차원축소 연산

In [27]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [28]:
np.sum(x)

10

In [29]:
x.sum()

10

In [30]:
x.min()

1

In [31]:
x.max()

4

In [32]:
x.argmin()

0

In [33]:
x.argmax()

3

In [34]:
x.mean()

2.5

## 고차원에서의 차원축소 연산

In [36]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [37]:
x.sum()

6

In [38]:
# 행방향 합치기 (열 별로 합치기)
x.sum(axis=0)

array([3, 3])

In [39]:
# 열방향 합치기 (행 별로 연산)
x.sum(axis=1)

array([2, 4])

## 정렬연산

In [40]:
a = np.array([[4,3,5,7],
              [1,12,11,9],
             [2,15,1,14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [43]:
# 행방향 정렬
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [44]:
# 열방향 정렬
np.sort(a,axis=1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [45]:
np.argsort(a,axis=0)

array([[1, 0, 2, 0],
       [2, 1, 0, 1],
       [0, 2, 1, 2]])